<?php
/**
 * Copyright © Ronan Guérin (@ronangr1) All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Ronangr1_SpookyEvent/js/screamer": {
                "imageUrl": "<?= $escaper->escapeJs($block->getViewFileUrl('Ronangr1_SpookyEvent/images/screamer.jpg')) ?>",
                    "audioUrl": "<?= $escaper->escapeJs($block->getViewFileUrl('Ronangr1_SpookyEvent/audio/screamer.mp3')) ?>",
                    "showScreamerKey": "<?= $escaper->escapeJs('show_screamer') ?>"
                }
            }
        }
</script>
